project:
  type: website
  execute-dir: project
  output-dir: _site
  preview:
    port: 6700
    host: 127.0.0.1
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Recipes"
  site-url: "https://lennartwittkuhn.com/recipes/"
  repo-url: "https://github.com/lnnrtwttkhn/recipes/"
  repo-branch: main
  issue-url: "https://github.com/lnnrtwttkhn/recipes/issues"
  repo-actions: [edit, source, issue]
  reader-mode: false
  navbar:
    title: false
    background: light
    search: true
    left:
      - href: index.qmd
        text: "{{< fa utensils >}} Recipes"
    right:
      - icon: envelope
        aria-label: Email
        href: "{{< var mailto >}}"
      - icon: github
        aria-label: GitHub
        href: "{{< var repo-url >}}"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    include-after-body: plausible.html
